### ISSUE TITLE
Youtube app share doesn't work

### ISSUE THREAD

**Issue by binarygeek119** [husudosu/metube-app#1]
I can't get the android youtube share to this app to work. sharing from other sites works.

**Comment by husudosu** [comment]
It works on my phones both on alpha and beta versions of the app. 

The expected behaviour should be something like this:
- You open Youtube select a video and share youtube Link into metube app
- Metube app opens with Open URL dialog with the video URL in it.
- You press open and it adds to Metube server for downloading.

Is the open URL dialog appears for you with Youtube URL in it when you share from Youtube app? Is there any error message or something?

**Comment by binarygeek119** [comment]
its working now i tried a differed video today. my guess is it was a previse downloaded video.
